### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by damiensedgwick**
This pull request removes a backslash that I am assuming is here by mistake. Due to being very minimal, I didn't see an issue being necessary but happy to create one if needed.

### CODE REVIEW

**Comment by jazware** [comment]
It's there to be compatible with different shells. Because the argument is not in quoted strings, some shells like zsh will get upset if you use a bare `?` in the argument.

**Comment by damiensedgwick** [comment]
> It's there to be compatible with different shells. Because the argument is not in quoted strings, some shells like zsh will get upset if you use a bare `?` in the argument.

Interesting, I did not realise this, does that mean that this example probably wants to be updated? 

A maximal example using all parameters looks like:
  
```bash
$ websocat "ws://localhost:6008/subscribe?wantedCollections=app.bsky.feed.post&wantedCollections=app.bsky.feed.like&wantedCollections=app.bsky.graph.follow&wantedDids=did:plc:q6gjnaw2blty4crticxkmujt&cursor=1725519626134432"
```

**Comment by jazware** [comment]
The argument to websocat in that case is in quotes so the `?` doesn't need escaping

**Comment by damiensedgwick** [comment]
> The argument to websocat in that case is in quotes so the `?` doesn't need escaping

My bad!

_Wonders off to get eyes tested_

**Pull request closed without merging**
